@startuml
scale 0.62
skinparam backgroundColor white
skinparam shadowing false
skinparam defaultFontName "Times New Roman"
skinparam defaultFontSize 14
skinparam dpi 180
skinparam ArrowThickness 1.4
hide footbox
skinparam sequence {
    ArrowColor #444444
    ArrowFontSize 15
    LifeLineBorderColor #777777
    LifeLineBackgroundColor #F7F7F7
    ParticipantBorderColor #444444
    ParticipantBackgroundColor #F2F2F2
    ParticipantPadding 2
    BoxPadding 2
}
skinparam participant<<ServerSpacer>> {
    BackgroundColor #F2F2F2
    BorderColor #F2F2F2
    FontColor #F2F2F2
}
skinparam participant<<ClientSpacer>> {
    BackgroundColor #E8F7E8
    BorderColor #E8F7E8
    FontColor #E8F7E8
}
skinparam sequenceLifeLineBorderColor<<ServerSpacer>> #F2F2F2
skinparam sequenceLifeLineBackgroundColor<<ServerSpacer>> #F2F2F2
skinparam sequenceLifeLineBorderColor<<ClientSpacer>> #E8F7E8
skinparam sequenceLifeLineBackgroundColor<<ClientSpacer>> #E8F7E8

box "Серверная часть" #F2F2F2
participant "DistMoEBlock" as Server
participant "HostPipelineTask" as HostTask
participant "TensorTransferEngine" as HostTTE
end box

box "Клиентская часть" #E8F7E8
participant "TensorTransferEngine" as ClientTTE
participant "DistExpertsBlock" as Client
participant "ExpertsBlockPipelineTask" as ExpertTask
end box

activate Server
Server -> HostTask : создать задачу
activate HostTask
HostTask -> HostTask : подготовка пакета\nметаданных
HostTask -> HostTTE : DispatchSubmit
HostTTE -> ClientTTE : DispatchSubmit

ClientTTE -> Client : метаданные
Client -> ExpertTask : создать задачу
activate ExpertTask
ExpertTask -> ClientTTE : read batch
HostTTE --> ClientTTE : чтение данных
ClientTTE --> ExpertTask : чтение данных
ExpertTask -> ExpertTask : экспертные\nвычисления
ExpertTask -> ClientTTE : write batch
ClientTTE --> HostTTE : запись данных
ExpertTask -> ClientTTE : HostOutputBuffer\nUnlocked
deactivate ExpertTask

ClientTTE -> HostTTE : HostOutputBuffer\nUnlocked
HostTTE -> Server : HostOutputBuffer\nUnlocked
Server -> HostTask : combine()
deactivate HostTask

deactivate Server
@enduml
